### PR TITLE
Add FFT to Scope.

### PR DESCRIPTION
**Pull request by benshayden**
Currently, Scope can show voltage, current, power, and a few other neat things.
It can sometimes guess the dominant frequency of the voltage.

However, one of the more useful features of real oscilloscopes that is still
missing is the ability to show the full Fourier transform of a signal.

This patch adds the "Show FFT" option to Scope.
Enabling this option will cause Scope to use the new FFT class to compute the
FFT of the voltage and paint the magnitude of the FFT as a bright red line
behind the voltage/current/power.

[Screenshot](http://imgur.com/um1uw85).

### CODE REVIEW

**Comment by sharpie7** [comment]
Hi Ben,

Thanks for submitting this. I saw your fork and wondered if it was a
personal project or if you might submit it to the main branch.

I am a bit busy at the moment but I'll take a look over the Christmas break
and get it included.

Iain

**Comment by benshayden** [comment]
Hi!

No rush. Playing with circuitjs is just for fun while my other code is compiling.
I also have a patch to load a full URL from location.hash, and a couple other ideas if you'd be interested.

Thanks for looking at the patch and thank you for circuitjs!

**Comment by sharpie7** [comment]
Thanks for submitting this - it's really cool. There does seem to be an odd bug though: try this circuit:

http://127.0.0.1:8888/circuitjs.html?cct=$+1+0.000005+38.696464541249114+50+5+50%0AO+448+240+656+240+0%0AR+208+240+128+240+0+1+50+5+0+0+0.5%0As+208+240+448+240+0+0+false%0Ao+0+64+0+1058+8.749002899132048+2.44140625e-105+0+-1%0A

(you might need to change the root URL)

Open the switch and wait for the scope to fill with zeros. Something very odd then happens to the FFT trace.

I also invite you to think about the vertical scale for the FFT. As the values are always +ve do you think the origin should be moved to show the trace more clearly?

On the question of loading circuits from location.hash - I think it's interesting but I've been reluctant to enable too many cross-site type features as (for the untrained user) this makes content from another site appear as-if it originated in the site hosting the app. What if someone created a pornographic circuit (PS - this is not meant as a challenge!) and then wrote a URL to it with the base address from another site?

Cheers

Iain

**Comment by Trass3r** [comment]
Any updates?

**Comment by pfalstad** [comment]
The bug is caused by the FFT object not getting destroyed and recreated when the size changes.  I fixed it here: https://github.com/pfalstad/circuitjs1/commit/58eac80d528dec4d9e555a192e64282ac4ae11c9

**Comment by sharpie7** [comment]
Incorporated in "one-year-updates" branch (via @pfalstad changes). Will merge to master in due course.

**Pull request closed without merging**
